### ISSUE TITLE
(HTML) Sections of code should not be commented out

### ISSUE THREAD

**Issue by DanielfQo** [DanielfQo/CRUD-PYTHON#23]

**Comment by KevinRodriguezLima** [comment]
**Descripción:**
"Los programadores no deben comentar código, ya que esto aumenta el tamaño de los programas y reduce su legibilidad.

El código no utilizado debe ser eliminado y se puede recuperar desde el historial de control de versiones si es necesario."

**Archivos:**

    my-app/templates/public/includes/messages.html
