### ISSUE TITLE
(JavaScript) Variables should be declared with "let" or "const"

### ISSUE THREAD

**Issue by DanielfQo** [DanielfQo/CRUD-PYTHON#30]

**Comment by LeonardoGB29** [comment]
**Descripción:** Se está utilizando la declaración var en lugar de let o const en el archivo JavaScript, lo cual no cumple con los estándares modernos de ES2015. Esto puede generar problemas de mantenibilidad y claridad en el código.

**Archivo:** my-app/static/assets/customJS/file.js
